### ISSUE TITLE
Downloading files result in empty data

### ISSUE THREAD

**Issue by jamogriff** [makeros3d/Octoprint-Makeros#1]
**Log of successful loading of file, followed by error when downloading:**
"_2020-11-19 19:51:18,956 - octoprint.plugins.MakerOS - INFO - Attempting to fetch project eYCKlGWHo12myHsUN6vNzj1R09oy from MakerOS
2020-11-19 19:51:24,439 - octoprint.plugins.MakerOS - INFO - Attempting to download file from MakerOS
2020-11-19 19:51:28,257 - octoprint.plugins.MakerOS - ERROR - There was an issue fetching MakerOS `files._"

Octoprint shows the files as downloaded successfully, but are empty files regardless of file type (.g-code or .stl).

**Comment by makeros3d** [comment]
Hey @jamogriff thanks for reporting this issue!

This turned out to be an issue with the way files were being written to storage during the download process.

Please check out the latest pull request #2 to see what was updated!

Let me know how this works for you and if you have any other issues. 

Thanks!
